_BASE_: "../../../../configs/Base-SBS.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True

  NUM_MODEL: 1
  HEADS:
    # Market1501 751, DukeMTMC 702, MSMT17 1041
    NUM_CLASSES: 702

INPUT:
  REA:
    ENABLED: False

SOLVER:
  FP16_ENABLED: True
#  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 10

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "projects/LDS/logs/DukeMTMC/Baseline"